version: '3.9'
services:
  nodejs:
    container_name: playmo-api-node
    image: 'playmo-api-node:latest'
    ports:
      - '8080:3000'
    build:
      context: ./nest
    restart: unless-stopped
    volumes:
      - ./nest:/var/www/nest
      - /var/www/nest/node_modules
    networks:
      - main

networks:
  main:
    external: true
    name: playmo

