version: "3"

networks:
  main:
    external: true
    name: playmo

services:
  nginx:
    container_name: playmo-api-nginx
    image: nginx:stable-alpine
    volumes:
      - ./php/api:/var/www/api
    depends_on:
      - php
      - mysql
    networks:
      - main

  mysql:
    platform: linux/x86_64
    image: mariadb
    container_name: playmo-api-mysql
    restart: unless-stopped
    tty: true
    volumes:
      - ./mysql/lib:/var/lib/mysql
      - ./mysql/initdb:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    networks:
      - main

  php:
    container_name: playmo-api-php
    build:
      context: ./php
      args:
        user: playmo
        uid: 1000
    ports:
      - "9000:9000"
    restart: unless-stopped
    volumes:
      - ./php/api:/var/www/api
      - ./php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - main
    working_dir: /var/www/api
